#! /bin/sh

### BEGIN INIT INFO FOR INSSERV
# Provides:          anturisagentservice
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts anturis agent service
# Description:       starts anturis agent service as a daemon
### END INIT INFO


### BEGIN INIT INFO FOR INSSERV
# chkconfig: 2345 80 80
# description: starts anturis agent service as a daemon
### END INIT INFO


DAEMON=/opt/anturis/bin/agent-service
DESC="Anturis Agent"

test -x $DAEMON || exit 0

case "$1" in
  start)
	echo "Starting $DESC"
	$DAEMON
	;;
  stop)
	echo "Stopping $DESC"
	$DAEMON -t
	;;
  restart|force-reload)
	echo "Restarting $DESC"
	$DAEMON -t
	$DAEMON
	;;
  status)
        $DAEMON -v
	;;
  *)
	echo "Usage: $NAME {start|stop|restart|status}" >&2
	exit 1
	;;
esac

exit 0
